=== SafBen/hello-world/SI4/Langages XML/TDs/TD1/DTD1.dtd
<!ELEMENT bde (student+)>
<!ELEMENT student (infospersonels,formation,emplois,skill,hobby) >
<!ELEMENT infospersonels (nom, prenom, adresse?, mobile?,email)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT formation (#PCDATA)>
<!ELEMENT emplois (#PCDATA)>
<!ELEMENT skill (langues,autres)>
<!ELEMENT langues (#PCDATA)>
<!ELEMENT autres (#PCDATA)>
<!ELEMENT hobby (#PCDATA)>

=== SafBen/hello-world/SI4/Langages XML/TDs/TD1/TD1.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="TD1.css"?>

<!DOCTYPE bde SYSTEM "DTD1.dtd">

<bde>
	<student>
		<infospersonels class="couleur">
			<nom>Benidir</nom>
			<prenom>Safwane</prenom>
			<adresse>Grasse</adresse>
			<mobile>1234</mobile>
			<email>adresse@gmail.com</email>
		</infospersonels>
		<formation>
		</formation>
		<emplois>
			Stage ouvrier 2018: bla bla bla
			Job d'été 2019: bla bla bla
		</emplois>
		<skill> <!-- xmlns:polytech="google.com" -->
			<langues>
				Anglais niveau B1
				Français natal
				Espagnol niveau B1
			</langues>
			<autres>
			</autres>
		</skill>
		<hobby>
			sport
		</hobby>
	</student>
</bde>
