=== SafBen/hello-world/SI4/Langages XML/TDs/TD2/TD2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="cv">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="titre"/>
				<xs:element type="xs:string" name="cvnom"/>
				<xs:element name="etatcivil">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="nom"/>
							<xs:element type="xs:string" name="prenom"/>
							<xs:element type="xs:date" name="naissance"/>
							<xs:element type="xs:string" name="situation"/>
							<xs:element type="xs:string" name="adresse"/>
							<xs:element name="code_postal">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="\d{5}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element type="xs:string" name="ville"/>
							<xs:element type="xs:string" name="pays"/>
							<xs:element name="telephone">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="\d{2}-\d{2}-\d{2}-\d{2}-\d{2}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element type="xs:string" name="email"/>
							<xs:element name="caracteristiques">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="caracteristique">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="type"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="formations">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="formation">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:date" name="date-iso"/>
											<xs:attribute type="xs:date" name="date"/>
											<xs:attribute type="xs:string" name="intitule"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element type="xs:string" name="connaissances"/>
				<xs:element name="professionnel">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="experience">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="missions">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="mission"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="environnement">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="technique">

														<xs:complexType>
															<xs:restriction base="xs:integer">
																<xs:minInclusive value="0"/>
																<xs:maxInclusive value="5"/>
															</xs:restriction>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:date" name="date-iso"/>
									<xs:attribute type="xs:date" name="date"/>
									<xs:attribute type="xs:string" name="entreprise"/>
									<xs:attribute type="xs:string" name="fonction"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SafBen/hello-world/SI4/Langages XML/TDs/TD2/TD2.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="TD2.css"?>


<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="TD2.xsd">
	<titre>
		texte
	</titre>
	<cvnom>
		texte
	</cvnom>
	<etatcivil>
		<nom>
			texte
		</nom>
		<prenom>
			texte
		</prenom>
		<naissance>2000-01-01</naissance>
		<situation>
			texte
		</situation>
		<adresse>
			texte
		</adresse>
		<code_postal>06130</code_postal>
		<ville>
			texte
		</ville>
		<pays>
			texte
		</pays>
		<telephone>01-02-03-04-05</telephone>
		<email>
			texte
		</email>
		<caracteristiques>
			<caracteristique type="type1">
				texte
			</caracteristique>
		</caracteristiques>
	</etatcivil>
	<formations>
		<formation date-iso="2000-01-01" date="2000-01-01" intitule="formation1"></formation>
	</formations>
	<connaissances></connaissances>
		<!-- </technique type="2" nom="name">
		</langue nom="anglais" niveau="B1"> -->
	
	<professionnel>
		<experience date-iso="2000-01-01" date="2000-01-01" entreprise="thales" fonction="fonction1">

			<missions>
				<mission>
					texte
				</mission>
			</missions>
			<environnement>
				<technique type="2">3</technique>
			</environnement>
		</experience>
	</professionnel>
	<!-- NE PEUX PAS APPRAITRE ICI MAIS UN AUTRE FICHIER XML POURRAIT PARTIR DE "PERSONNEL" COMME RACINE 
		<personnel>
		<activite type="type2" nom="nom_activite">
			texte
		</activite>
	</personnel> -->
</cv>
