<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="TD2.css"?>

<!DOCTYPE cv
[
<!ELEMENT cv (titre, cvnom, etatcivil, formations, connaissances, professionnel)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT cvnom (#PCDATA)>
<!ELEMENT etatcivil
 (nom, prenom, naissance, situation, adresse?, code_postal?, ville?, pays?, telephone?, email?,caracteristiques?)>
<!ELEMENT caracteristiques (caracteristique+)>
<!ELEMENT formations (formation+)>
<!ELEMENT connaissances (technique*, langue*)>
<!ELEMENT professionnel (experience+)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT naissance (#PCDATA)>
<!ELEMENT situation (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT code_postal (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT pays (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT caracteristique (#PCDATA)>
<!ATTLIST caracteristique
   type CDATA #REQUIRED>
<!ELEMENT formation EMPTY>
<!ATTLIST formation
   date-iso CDATA #REQUIRED
   date CDATA #REQUIRED
   datefin CDATA #IMPLIED
   intitule CDATA #REQUIRED
   description CDATA #IMPLIED>
<!ELEMENT technique EMPTY>
<!ATTLIST technique
   type (0 | 1 | 2| 3 | 4 | 5) #REQUIRED
   nom CDATA #REQUIRED
   description CDATA #IMPLIED>
<!ELEMENT langue EMPTY>
<!ATTLIST langue
   nom CDATA #REQUIRED
   niveau CDATA #REQUIRED>
<!ELEMENT experience (missions, environnement)>
<!ATTLIST experience
   date-iso CDATA #REQUIRED
   date CDATA #REQUIRED
   datefin CDATA #IMPLIED
   client CDATA #IMPLIED
   entreprise CDATA #REQUIRED
   fonction CDATA #REQUIRED>
<!ELEMENT missions (mission+)>
<!ELEMENT environnement (technique+)>
<!ELEMENT mission (#PCDATA)>
<!ELEMENT personnel (activite*)>
<!ELEMENT activite (#PCDATA)>
<!ATTLIST activite
   type CDATA #REQUIRED
   nom CDATA #REQUIRED
   description CDATA #IMPLIED>
]>

<cv>
	<titre>
		texte
	</titre>
	<cvnom>
		texte
	</cvnom>
	<etatcivil>
		<nom>
			texte
		</nom>
		<prenom>
			texte
		</prenom>
		<naissance>
			texte
		</naissance>
		<situation>
			texte
		</situation>
		<adresse>
			texte
		</adresse>
		<code_postal>
			texte
		</code_postal>
		<ville>
			texte
		</ville>
		<pays>
			texte
		</pays>
		<telephone>
			texte
		</telephone>
		<email>
			texte
		</email>
		<caracteristiques>
			<caracteristique type="type1">
				texte
			</caracteristique>
		</caracteristiques>
	</etatcivil>
	<formations>
		<formation date-iso="01/01/2000" date="texte" intitule="formation1"></formation>
	</formations>
	<connaissances></connaissances>
		<!-- </technique type="2" nom="name">
		</langue nom="anglais" niveau="B1"> -->
	
	<professionnel>
		<experience date-iso="01/01/2000" date="texte" entreprise="thales" fonction="fonction1">

			<missions>
				<mission>
					texte
				</mission>
			</missions>
			<environnement>
				<technique type="2" nom="name"></technique>
			</environnement>
		</experience>
	</professionnel>
	<!-- NE PEUX PAS APPRAITRE ICI MAIS UN AUTRE FICHIER XML POURRAIT PARTIR DE "PERSONNEL" COMME RACINE 
		<personnel>
		<activite type="type2" nom="nom_activite">
			texte
		</activite>
	</personnel> -->
</cv>